version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: challengedb
    ports:
      - "5432:5432"
  web:
    image: backend-challenge-node-app
    depends_on:
      - db
    ports:
      - "4000:4000"